version: "3"
services:
    api:
        build: "./api"
        container_name: "api"
        ports: 
            - "80:80"
        depends_on:
            - redis
    redis:
        image: redis:latest
        container_name: "redis"
        ports: 
            - "6379:6379"

